
/*
    Banco de Dados utilizado: SQL Server Express LocalDB
    Registros das entidades geradas em: https://www.4devs.com.br/gerador_de_empresas
*/

-- [FORNECEDOR]
CREATE TABLE [dbo].[FORNECEDOR] (
    [ID_FORNECEDOR]   INT           IDENTITY (1, 1) NOT NULL,
    [CNPJ]            VARCHAR (14)  NULL,
    [CPF]             VARCHAR (11)  NULL,
    [NOME]            VARCHAR (50)  NOT NULL,
    [EMAIL]           VARCHAR (100) NOT NULL,
    [CEP]             VARCHAR (8)   NOT NULL,
    [RG]              VARCHAR (9)   NULL,
    [DATA_NASCIMENTO] DATE          NULL,
    [TIPO_FORNECEDOR] CHAR (1)      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_FORNECEDOR] ASC),
    CHECK ([TIPO_FORNECEDOR]='J' OR [TIPO_FORNECEDOR]='F'),
    CONSTRAINT [TIPO_FORNECEDOR] CHECK ([TIPO_FORNECEDOR]='J' OR [TIPO_FORNECEDOR]='F')
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__FORNECED__RG]
    ON [dbo].[FORNECEDOR]([RG] ASC) WHERE ([RG] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__FORNECED__CPF]
    ON [dbo].[FORNECEDOR]([CPF] ASC) WHERE ([CPF] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__FORNECED__CNPJ]
    ON [dbo].[FORNECEDOR]([CNPJ] ASC) WHERE ([CNPJ] IS NOT NULL);

-- [EMPRESA]
CREATE TABLE [dbo].[EMPRESA] (
    [ID_EMPRESA]    INT           IDENTITY (1, 1) NOT NULL,
    [CNPJ]          VARCHAR (14)  NOT NULL,
    [NOME_FANTASIA] VARCHAR (100) NOT NULL,
    [CEP]           VARCHAR (8)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_EMPRESA] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__EMPRESA__CNPJ]
    ON [dbo].[EMPRESA]([CNPJ] ASC) WHERE ([CNPJ] IS NOT NULL);

-- [CONTRATO]
CREATE TABLE [dbo].[CONTRATO] (
    [ID_CONTRATO]   INT IDENTITY (1, 1) NOT NULL,
    [ID_EMPRESA]    INT NOT NULL,
    [ID_FORNECEDOR] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_CONTRATO] ASC),
    FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA]),
    FOREIGN KEY ([ID_FORNECEDOR]) REFERENCES [dbo].[FORNECEDOR] ([ID_FORNECEDOR])
);

